
DROP TABLE IF EXISTS company.ANALYSIS_PARAMETER CASCADE;
DROP TABLE IF EXISTS company.ANALYSIS CASCADE;
DROP TABLE IF EXISTS company.INSTRUMENT CASCADE;
DROP TABLE IF EXISTS company.SAMPLE CASCADE;
DROP TABLE IF EXISTS company.EQU_LOCATION CASCADE;
DROP TABLE IF EXISTS company.EQUIPMENT CASCADE;
DROP TABLE IF EXISTS company.PROCESS_OUTPUT CASCADE;
DROP TABLE IF EXISTS company.PROCESS_INPUT CASCADE;
DROP TABLE IF EXISTS company.PROCESS CASCADE;
DROP TABLE IF EXISTS company.MATERIAL CASCADE;
DROP TABLE IF EXISTS company.EXPERIMENT CASCADE;
DROP TABLE IF EXISTS company.SCIENTIST CASCADE;

